TOPDIR = ..\..

# configuration, adapt before building

# base installation dir of WIX
WIX_DIR = C:\Program Files\Wix Toolset v3.8

# where is Qt installed
#QT_DIR = C:\Qt\Qt5.2.1\5.2.1\msvc2010
QT_DIR = C:\Qt\4.8.6

# where is OpenSSL installed
OPENSSL_DIR = C:\develop\openssl-1.0.1g-win32-debug

# libraries to link into the installer
WIX_LIBS = dutil_2008.lib wcautil_2008.lib
#WIX_LIBS = dutil_2008_x64.lib wcautil_2008_x64.lib

# architecture of resulting msi
WIX_ARCH = x86
#WIX_ARCH = x64

# define if you want to deploy the debug version
DEBUG = 1

# define for SSL support
WITH_SSL = 1

# set correct major version of Qt
QT_MAJOR_VERSION = 4
#QT_MAJOR_VERSION = 5

# end configuration

CANDLE = "$(WIX_DIR)\bin\candle.exe"
LIGHT = "$(WIX_DIR)\bin\light.exe"
LIT = "$(WIX_DIR)\bin\lit.exe"
SMOKE = "$(WIX_DIR)\bin\smoke.exe"
SETUPBLD = "$(WIX_DIR)\bin\setupbld.exe"

WIX_FLAGS = \
	-dqt_dir=$(QT_DIR)

WIX_FLAGS = $(WIX_FLAGS) \
	-dtopdir=$(TOPDIR)
	
!IFDEF DEBUG
WIX_FLAGS = $(WIX_FLAGS) \
	-ddebug=1 -dbuilddir=debug
!ELSE
WIX_FLAGS = $(WIX_FLAGS) \
	-dbuilddir=release
!ENDIF

!IFDEF WITH_SSL
WIX_FLAGS = $(WIX_FLAGS) \
	-dwith_ssl=1 \
	-dopenssl_dir=$(OPENSSL_DIR)
!ENDIF

WIX_FLAGS = $(WIX_FLAGS) \
	-dqt_version=$(QT_MAJOR_VERSION)

WIX_EXTENSIONS = \
	-ext WixUIExtension -ext WixUtilExtension
	
WIX_OBJS = \
	wolfclient.wixobj \
	WixUI_wolfclient.wixobj

WIX_LOCALES = \
	-cultures:en-us -loc "i18n\en_us-wolfclient.wxl"
	
.SUFFIXES: .wxs .wixobj

.wxs.wixobj:
	$(CANDLE) /nologo -o $@ -arch $(WIX_ARCH) $(WIX_FLAGS) $(WIX_EXTENSIONS) $<

all: wolfclient.msi

wolfclient.msi: $(WIX_OBJS)
	$(LIGHT) /nologo -o $@ $(WIX_FLAGS) $(WIX_EXTENSIONS) $(WIX_LOCALES) $**

setup.exe: wolfclient.msi
	$(SETUPBLD) -out setup.exe -ms wolfclient.msi -setup "$(WIX_DIR)\bin\setup.exe"

clean:
	@-erase *.wixobj wolfclient.wixpdb wolfclient.msi setup.exe *.log 2>NUL

distclean: clean

test: wolfclient.msi
	$(SMOKE) wolfclient.msi

test_install:
	-del install.log
	-msiexec /lieva install.log /i wolfclient.msi

test_uninstall:
	-del uninstall.log
	-msiexec /lieva uninstall.log /x {f0620f88-b93f-4699-a55b-44bf2b30cfca}
